// Dev-only: regenerates migrations/001_auth.sql from Better Auth's schema.
// Run after upgrading better-auth or changing buildAuthOptions(): `npx tsx scripts/gen-auth-sql.ts`
import Database from "better-sqlite3";
import fs from "node:fs";
import { getMigrations } from "better-auth/db/migration";
import { buildAuthOptions } from "../src/lib/auth";

async function main() {
  const db = new Database(":memory:");
  const { compileMigrations } = await getMigrations({ ...buildAuthOptions(), database: db });
  const sql = await compileMigrations();
  fs.writeFileSync("migrations/001_auth.sql", `-- Generated by scripts/gen-auth-sql.ts (Better Auth schema). Do not edit by hand.\n${sql}\n`);
  console.log(sql);
}
main();
